# Site settings
title: CV Benchtops and Hardware
url: http://cvbenchtops.com.au
email: sales@cvbenchtops.com.au
street_address: 80 Powells Avenue
city: Bendigo
state: VIC
postcode: 3550
phone: 03 5443 1260
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

timezone: Australia/Melbourne
permalink: /:year/:month/:day/:title.html

sass:
    sass_dir: /assets/css/_sass
    style: :compressed

exclude: [vendor]

gems:
  - jekyll-sitemap

